USE KODILLA_COURSE;

DELIMITER $$
CREATE EVENT UPDATE_BESTSELLERS
ON SCHEDULE EVERY 1 MINUTE
DO
BEGIN
	DECLARE BESTSELLER_VALUE INT;
	CALL UpdateBestsellers();
    SELECT BESTSELLERS_COUNT INTO BESTSELLER_VALUE;
    INSERT INTO STATS (STAT_DATE, STAT, VALUE)
		VALUES (CURDATE(), "BESTSELLERS", BESTSELLER_VALUE);
END $$
DELIMITER ; 
