DROP TRIGGER STATS_INSERT;

DELIMITER $$

CREATE TRIGGER STATS_INSERT AFTER INSERT ON STATS
FOR EACH ROW
BEGIN
INSERT INTO bestsellers_count (STAT_ID, STAT_DATE, STAT, VALUE)
	VALUES (1, CURDATE(), 2, BESTSELLERS);
  
END $$

DELIMITER ;
 COMMIT;
 
 SELECT * FROM STATS;
