DELIMITER $$

CREATE TRIGGER BOOKS_UPDATE AFTER UPDATE ON BOOKS
FOR EACH ROW
BEGIN
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_RENT_ID, NEW_READER_ID,
							NEW_RENT_DATE, NEW_RETURN_DATE, OLD_RENT_ID, OLD_READER_ID,
                            OLD_RENT_DATE, OLD_RETURN_DATE)
          VALUES (CURTIME(), "UPDATE", OLD.BOOK_ID, NEW.RENT_ID, NEW.READER_ID,
				NEW.RENT_DATE, NEW.RETURN_DATE, OLD.RENT_ID, OLD.READER_ID,
                OLD.RENT_DATE, OLD.RETURN_DATE);
END $$

DELIMITER ;