DELIMITER $$

CREATE TRIGGER READERS_UPDATE AFTER UPDATE ON READERS
FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_BOOK_ID, NEW_RENT_ID, 
							NEW_RENT_DATE, NEW_RETURN_DATE, OLD_BOOK_ID, OLD_RENT_ID,
                            OLD_RENT_DATE, OLD_RETURN_DATE)
          VALUES (CURTIME(), "UPDATE", OLD.READER_ID, NEW.BOOK_ID, NEW.RENT_ID,
				NEW.RENT_DATE, NEW.RETURN_DATE, OLD.BOOK_ID, OLD.RENT_ID,
                OLD.RENT_DATE, OLD.RETURN_DATE);
END $$

DELIMITER ;